{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1",
    "description": "Rswag Blog API"
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ],
  "paths": {
    "/articles": {
      "get": {
        "summary": "list articles",
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "author": "Vulputate Ut",
                    "title": "Vulputate Mi Sit 1",
                    "body": " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam libero justo laoreet sit. Viverra suspendisse potenti nullam ac. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Ipsum dolor sit amet consectetur.",
                    "created_at": "2021-10-14T19:25:56.477Z",
                    "updated_at": "2021-10-14T19:25:56.477Z",
                    "url": "http://www.example.com/articles/1"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "create article",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "successful",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "author": "Test Author",
                  "title": "Title",
                  "body": "Lorem Ipsum Body.",
                  "created_at": "2021-10-14T19:25:56.515Z",
                  "updated_at": "2021-10-14T19:25:56.515Z",
                  "url": "http://www.example.com/articles/1"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "article": {
                    "type": "object",
                    "properties": {
                      "author": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "body": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/articles/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show article",
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "author": "Vulputate Ut",
                  "title": "Vulputate Mi Sit 2",
                  "body": " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam libero justo laoreet sit. Viverra suspendisse potenti nullam ac. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Ipsum dolor sit amet consectetur.",
                  "created_at": "2021-10-14T19:25:56.520Z",
                  "updated_at": "2021-10-14T19:25:56.520Z",
                  "url": "http://www.example.com/articles/1"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "update article",
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "author": "Vulputate Ut",
                  "title": "Title",
                  "body": " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam libero justo laoreet sit. Viverra suspendisse potenti nullam ac. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Ipsum dolor sit amet consectetur.",
                  "created_at": "2021-10-14T19:25:56.530Z",
                  "updated_at": "2021-10-14T19:25:56.537Z",
                  "url": "http://www.example.com/articles/1"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "article": {
                    "type": "object",
                    "properties": {
                      "author": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "body": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update article",
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "example": {
                  "id": 1,
                  "author": "Vulputate Ut",
                  "title": "Title",
                  "body": " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut consequat semper viverra nam libero justo laoreet sit. Viverra suspendisse potenti nullam ac. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Ipsum dolor sit amet consectetur.",
                  "created_at": "2021-10-14T19:25:56.540Z",
                  "updated_at": "2021-10-14T19:25:56.547Z",
                  "url": "http://www.example.com/articles/1"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "article": {
                    "type": "object",
                    "properties": {
                      "author": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "body": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete article",
        "responses": {
          "204": {
            "description": "no content",
            "content": {
              "application/json": {
              }
            }
          }
        }
      }
    }
  }
}