{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1",
    "description": "This is the first version of my API"
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ],
  "paths": {
    "/articles": {
      "get": {
        "summary": "list articles",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "post": {
        "summary": "create article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/articles/new": {
      "get": {
        "summary": "new article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/articles/{id}/edit": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "edit article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/articles/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "patch": {
        "summary": "update article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "put": {
        "summary": "update article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "delete": {
        "summary": "delete article",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    }
  }
}